### ISSUE TITLE
loggedMessages is assumed to be in "userplugins" directory

### ISSUE THREAD

**Issue by ivystopia** [zastlx/vc-stalker-plugin#1]
Installation will fail if user is using `plugins` directory instead of `userplugins`

I have prepared a hacky patch I'm already using to fix this. Tested it in both cases.

**Comment by zastlx** [comment]
Thank you, I have fixed this in https://github.com/zastlx/vc-stalker-plugin/commit/92cd1647f46e1f093221b30b5976adce1756c013
