### ISSUE TITLE
Feature Request: Option to change the word "Stalk" to something more benign

### ISSUE THREAD

**Issue by ivystopia** [zastlx/vc-stalker-plugin#12]
For many reasons, some people would prefer not to have text such as "Stalk User" appearing in their Discord client.

Proposing an option to change this to something more innocent:

- Monitor user
- Manage user
- Subscribe to user
- Alert on user
- **Suggestions welcome**

I am working on this in my free time.

**Comment by ivystopia** [comment]
To be clear, I mean, the default wording would stay default.
But there would be an option in settings to change it to something else.

**Comment by VillainsRule** [comment]
bro's parents are checking 😭

**Comment by ivystopia** [comment]
I'm not making any assumptions about anyone's environment.
I feel the plugin provides a useful feature, but it has something of a "branding problem"

I'm considering hard forking and maintaining the repo under a new name, @zastlx please reach out to me if you'd like to discuss that.
